import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@web/providers/AuthProvider";
import Header from "@web/components/Header";
import Sidebar from "@web/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`h-screen ${inter.className}`}>
				<AuthProvider>
					<div className="flex h-screen flex-col">
						<Header />
						<div className="flex flex-1 overflow-hidden">
							<Sidebar />
							<main className="flex-1 overflow-y-auto">{children}</main>
						</div>
					</div>
				</AuthProvider>
			</body>
		</html>
	);
}
