import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@web/providers/AuthProvider";
import Header from "@web/components/Header";
import { SidebarProvider } from "@web/providers/SidebarProvider";
import StarryBackground from "@web/components/StarryBackground";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "The Greatest Social Media Site | Socialyze",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={`h-screen ${inter.className}`}>
				<SidebarProvider>
					<AuthProvider>
						<div className="flex h-screen flex-col">
							<Header />
							<StarryBackground />
							<div className="z-10 flex-1 overflow-hidden">{children}</div>
						</div>
					</AuthProvider>
				</SidebarProvider>
			</body>
		</html>
	);
}
