name: Backend CI

on:
    pull_request:
        paths:
            - "apps/api/**"
            - "packages/shared/**"
            - ".eslintrc.js"
            - "package.json"
            - "pnpm-lock.yaml"
            - "tsconfig.json"

jobs:
    lint-and-test:
        runs-on: ubuntu-latest
        env:
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
        defaults:
            run:
                working-directory: ./apps/api
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build shared package
              run: pnpm --filter @socialyze/shared run build

            - name: Run lint
              run: pnpm run lint

            - name: Run tests
              run: pnpm run test -- --ci --reporter=spec

            - name: Cache pnpm store
              uses: actions/cache@v3
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-
