name: Deploy to EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup SSH key
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa

            - name: Add EC2 to known hosts
              run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

            - name: Deploy app
              run: |
                  ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
                    set -e

                    APP_DIR=/var/www/socialyze

                    if [ ! -d "$APP_DIR" ]; then
                      mkdir -p $APP_DIR
                      git clone https://github.com/Meeran-Tofiq/socialyze.git $APP_DIR
                    fi

                    cd $APP_DIR

                    echo ">> Stopping all PM2 apps (if any)..."
                    pm2 stop all || echo "No PM2 processes to stop"

                    echo ">> Pulling latest code..."
                    git pull origin main

                    echo ">> Setting up pnpm..."
                    corepack enable
                    corepack prepare pnpm@latest --activate

                    echo ">> Installing dependencies..."
                    pnpm install --frozen-lockfile

                    echo ">> Building shared package..."
                    pnpm --filter shared build || (echo "Shared build failed" && exit 1)

                    echo ">> Building frontend..."
                    pnpm --filter web build || (echo "Web build failed" && exit 1)

                    echo ">> Building backend..."
                    pnpm --filter api build || (echo "API build failed" && exit 1)

                    echo ">> Restarting PM2 apps..."
                    pm2 start ecosystem.config.js --env production || pm2 restart ecosystem.config.js --env production || (echo "PM2 failed" && exit 1)

                    pm2 save
                  EOF
